# Generated by Django 4.0.5 on 2022-06-27 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_comment_listing_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.CharField(default='q', max_length=500),
            preserve_default=False,
        ),
    ]
