# Generated by Django 4.0.5 on 2022-06-28 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(default='other', max_length=100),
        ),
    ]
